version: '3.1'
networks:
  ? jurandir
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=jurandir
      - POSTGRES_USER=jurandir
    networks:
      - jurandir
    ports:
      - 5432:5432
  # jurandir:
  #   container_name: jurandir
  #   image: jurandir
  #   hostname: jurandir
  #   environment:
  #     - BOT_TOKEN: "bot_token"
  #     - BOT_ID: "bot_id"
  #     - BOT_SECRET: "bot_secret"
  #     - GUILD_ID: "guild_id"
  #     - KOBOLDAI_API: https://koboldai-api.com
  #     - GPT_PROPERTIES_TEMPERATURE: 0.8
  #     - GPT_PROPERTIES_P_VALUE: 0.8
  #     - GPT_PROPERTIES_MAX_TOKENS: 100
  #     - GPT_PROPERTIES_MIN_TOKENS: 5
  #     - DATABASE_PASSWORD: jurandir
  #     - DATABASE_USER: jurandir
  #     - DATABASE_URL: "postgres:5432"
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - jurandir