logging.file.name: logs/jurandir.log
server.port: ${PORT:8080}

spring:
  application.name: Jurandir
  redis:
    host: localhost
    port: 6370

jurandir:
  discord:
    message.operator: /j
    api:
      token: ${BOT_TOKEN}
      id: ${BOT_ID}
      secret: ${BOT_SECRET}
  gpt:
    server: ${KOBOLDAI_API}
